const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto').webcrypto;
const html=fs.readFileSync('web/index.html','utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
// Exercise the real page script against a persistent fake service. Reads never execute model work.
class El {
 constructor(tag='div'){this.tag=tag;this.children=[];this.textContent='';this.dataset={};this.style={};this.attributes={};this.value='';}
 append(...e){this.children.push(...e);}replaceChildren(...e){this.children=e;}setAttribute(k,v){this.attributes[k]=v;}
 showModal(){this.open=true;}close(){this.open=false;}focus(){}select(){this.selected=true;}
}
const clone=v=>JSON.parse(JSON.stringify(v)),flatten=e=>[e,...e.children.flatMap(flatten)];
function service(){return {jobs:[],details:new Map(),submissions:new Map(),worker_supported:true};}
function sample(id,account,kind='visual',verdict='pass'){return {id,account_id:account,model:'gpt-other',reasoning_effort:'medium',started_at_ms:Date.now()-1800,completed_at_ms:Date.now(),duration_ms:1800,request_id:'request-'+id,output:kind==='visual'?'<!doctype html><html><head></head><body><svg><text>Pelican '+account+'</text></svg><script>window.PWNED=true</script></body></html>':'最少取出21颗糖果。',prompt:kind==='visual'?'鹈鹕提示词':'糖果原题',status:'completed',error:null,assessment:kind==='logic'?{verdict,answer:verdict==='pass'?21:29,note:'明确的最终答案'}:null};}
function complete(server,id,results){const batch=server.jobs.find(b=>b.items.some(i=>i.id===id)),item=batch.items.find(i=>i.id===id);item.status='completed';item.completed=item.total;item.completed_at_ms=Date.now();server.details.set(id,{item,kind:batch.kind,model:batch.model,reasoning_effort:batch.reasoning_effort,results});if(batch.items.every(i=>i.status==='completed'||i.status==='cancelled'))batch.status='completed';}
async function boot({server=service(),settingsPage=false,settingsFailure=null,customOutput=4096,missingAccount=false,submitFailure=false}={}){
 const els=new Map(),listeners={},timers=new Map(),ctx={TextDecoder,Date,Number,JSON,Boolean,Error,console,encodeURIComponent,crypto,setTimeout(fn){const id=timers.size+1;timers.set(id,fn);return id;},clearTimeout(id){timers.delete(id);}};
 let reads=0,evidenceReads=0,visualReads=0,logicReads=0,reviews=0,settingsReads=0,settingsPosts=0,jobCreates=0,jobReads=0,jobLists=0,jobCancels=0;
 const accounts=['one','two'].map(id=>({account_id:'acct-'+id,name:'OpenAI '+id,email:id+'@example.test',enabled:true,quality:{phase:'pending',lease_until_ms:0,next_probe_at_ms:0},batch:null,history:[],last_sample:null,visual_tests:[],logic_tests:[]}));
 const status={enabled:true,key_scopes_ok:true,probe_budget_ok:true,auto_probe:false,maintenance:{ok:true},model:'gpt-test',visual_models:['gpt-test','gpt-other','gpt-6-astra'],visual_efforts:['low','medium','high'],visual_timeout_ms:570000,probe_limits:{max_daily_attempts:12,max_output_tokens:4096,max_daily_output_tokens:49152},budget:{day:Math.floor(Date.now()/86400000),attempts:0,reserved_output_tokens:0},accounts};
 const settings={revision:7,config:{enabled:true,auto_probe:false,account_ids:missingAccount?['acct-one','acct-missing']:['acct-one'],model:'gpt-test',max_daily_attempts:6,max_output_tokens:customOutput},accounts:[...accounts.map(({account_id,name,email,enabled})=>({account_id,name,email,enabled})),{account_id:'acct-disabled',name:'Unavailable <script>',enabled:false}],models:status.visual_models,fixed:{confidence_threshold:.99,max_daily_output_tokens:30000,probe_daily_usd:'5',probe_weekly_usd:'25',max_quarantined_percent:50,business_key_ids:['key-untouched'],policy:{samples_per_round:3,anomaly_rounds:2,recovery_rounds:2,anomaly_spacing_ms:300000,recovery_spacing_ms:600000,healthy_interval_ms:3600000,unknown_retry_ms:300000,cooldown_initial_ms:3600000,cooldown_max_ms:86400000}}},settingsPayloads=[],jobPayloads=[];
 ctx.document={getElementById:id=>{if(!els.has(id)){const el=new El();if(id==='visual-count')el.value='1';if(id==='visual-effort')el.value='medium';els.set(id,el);}return els.get(id);},createElement:tag=>new El(tag),documentElement:new El('html'),execCommand:command=>command==='copy'};
 ctx.DOMParser=class{parseFromString(source,type){assert.equal(type,'text/html');return {documentElement:{source}};}};ctx.XMLSerializer=class{serializeToString(e){return '<html xmlns="http://www.w3.org/1999/xhtml">'+e.source+'</html>';}};
 ctx.window={addEventListener(name,fn){listeners[name]=fn;},codexProxyPlugin:{theme:'dark',page:{id:settingsPage?'probe-settings':'quality-probes'},async request({method,path,body}){
  const input=body?JSON.parse(body):null,account=input?accounts.find(a=>a.account_id===input.account_id):null;let result;
  if(path==='settings'){
   if(method==='GET'){settingsReads++;result=clone(settings);}else{settingsPosts++;settingsPayloads.push(input);if(settingsFailure)return {status:409,body:new TextEncoder().encode(JSON.stringify({error:settingsFailure})).buffer};assert.equal(input.expected_revision,settings.revision);const {expected_revision,...next}=input;if(next.max_daily_attempts!==settings.config.max_daily_attempts||next.max_output_tokens!==settings.config.max_output_tokens)settings.fixed.max_daily_output_tokens=next.max_daily_attempts*next.max_output_tokens;settings.config=clone(next);settings.revision++;result={status:'settings_saved',revision:settings.revision};}
  }else if(path==='status'&&method==='GET'){reads++;result=clone(status);for(const a of result.accounts){for(const t of a.batch?.attempts||[]){delete t.prompt;delete t.output;}for(const t of [...a.visual_tests,...a.logic_tests]){delete t.prompt;delete t.output;}}}
  else if(path==='jobs'&&method==='GET'){jobLists++;result={batches:server.jobs,worker_supported:server.worker_supported,history_limit:100};}
  else if(path==='jobs'&&method==='POST'){
   jobCreates++;jobPayloads.push(input);assert.match(input.submission_id,/^[a-f0-9-]{36}$/);assert(input.account_ids.every(id=>accounts.some(a=>a.account_id===id)));let batch=server.submissions.get(input.submission_id);
   if(!batch){batch={id:'batch-'+server.jobs.length,kind:input.kind,model:input.model||status.model,reasoning_effort:input.reasoning_effort||'low',repetitions:input.repetitions,created_at_ms:Date.now(),status:'queued',items:input.account_ids.map((account_id,i)=>({id:'job-'+server.jobs.length+'-'+i,account_id,status:'queued',completed:0,total:input.kind==='fingerprint'?3:input.repetitions,error:null}))};server.jobs.unshift(batch);server.submissions.set(input.submission_id,batch);for(const item of batch.items)server.details.set(item.id,{item,kind:batch.kind,model:batch.model,reasoning_effort:batch.reasoning_effort,results:[]});}
   if(submitFailure)throw new Error('network response lost');result={status:'queued',job_id:batch.id,batch,replayed:jobCreates>1};
  }else if(path==='job'){jobReads++;assert.equal(method,'POST');result=server.details.get(input.id);assert(result,'known task detail');}
  else if(path==='job-cancel'){jobCancels++;const batch=server.jobs.find(b=>b.id===input.id);assert(batch);for(const item of batch.items)if(item.status==='queued')item.status='cancelled';batch.status=batch.items.some(i=>i.status==='running')?'running':'cancelled';result={status:'jobs_cancelled'};}
  else if(path==='evidence'){evidenceReads++;assert(account);result={account_id:account.account_id,batch:account.batch,history:account.history,quality:account.quality};}
  else if(path==='visual-evidence'||path==='logic-evidence'){assert(account);if(path==='visual-evidence')visualReads++;else logicReads++;const kind=path.split('-')[0];result={account_id:account.account_id,[kind+'_tests']:account[kind+'_tests']};}
  else if(path==='visual-review'){reviews++;assert(account);const output=[...server.details.values()].flatMap(d=>d.results).find(r=>r.id===input.sample_id)||account.visual_tests.find(r=>r.id===input.sample_id);assert(output);output.assessment={verdict:input.verdict,source:'manual'};result={status:'visual_reviewed',account_id:account.account_id,visual_sample:output};}
  else throw new Error('Unexpected route (browser must never execute models): '+method+' '+path);
  return {status:200,body:new TextEncoder().encode(JSON.stringify(result)).buffer};
 }}};
 vm.createContext(ctx);vm.runInContext(script,ctx);await new Promise(setImmediate);
 return {ctx,els,server,status,settings,settingsPayloads,jobPayloads,listeners,timers,run:code=>vm.runInContext(code,ctx),counts:()=>({reads,evidenceReads,visualReads,logicReads,reviews,settingsReads,settingsPosts,jobCreates,jobReads,jobLists,jobCancels,posts:0,visualPosts:0,logicPosts:0})};
}
(async()=>{
 let r=await boot();assert.equal(r.counts().jobCreates,0);assert.equal(r.counts().jobLists,1);assert.equal(r.run('batchAccounts.size'),1);assert.equal(r.els.get('visual-model').value,'gpt-6-astra');assert.equal(r.els.get('start').disabled,false);assert.equal(r.ctx.document.documentElement.dataset.theme,'dark');
 r.run("$('batch-all').checked=true;$('batch-all').onchange();mode='visual';$('visual-model').value='gpt-other';$('visual-count').value='2';render()");await r.run('submitJobs()');assert.equal(r.counts().jobCreates,1);assert.deepEqual(r.jobPayloads[0].account_ids,['acct-one','acct-two']);assert.equal(r.jobPayloads[0].repetitions,2);assert.equal(r.jobPayloads[0].reasoning_effort,'medium');assert.equal(r.run('busy'),false);assert.match(r.els.get('notice').textContent,/批次已保存.*可关闭/);assert.equal(r.els.get('start').disabled,true);assert.equal(r.server.jobs[0].items.length,2);assert.equal(r.run('jobDetail.results.length'),0);
 const server=r.server,batch=server.jobs[0],first=batch.items[0],second=batch.items[1];batch.status='running';first.status='running';await r.run('pollJobs()');assert.equal(r.counts().jobCreates,1);assert(flatten(r.els.get('jobs')).some(e=>String(e.textContent).includes('执行中')));r.listeners.pagehide();assert.equal(r.run('pageClosed'),true);assert.equal(r.timers.size,0);
 // A new page can recover an in-progress saved batch without creating any work.
 let reopen=await boot({server});assert.equal(reopen.counts().jobCreates,0);assert.equal(reopen.counts().jobReads,1);assert.equal(reopen.run('selectedJobId'),first.id);assert.match(reopen.els.get('job-banner').textContent,/acct-one/);assert.equal(reopen.els.get('start').disabled,true);assert.deepEqual(Array.from(reopen.run('batchAccounts')),['acct-one','acct-two']);assert.equal(reopen.els.get('visual-count').value,'2');assert.equal(reopen.els.get('visual-model').value,'gpt-other');assert.equal(reopen.els.get('visual-effort').value,'medium');
 reopen.run("batchAccounts=new Set(['acct-two']);$('visual-count').value='4'");await reopen.run('pollJobs()');assert.deepEqual(Array.from(reopen.run('batchAccounts')),['acct-two']);assert.equal(reopen.els.get('visual-count').value,'4');assert.equal(reopen.counts().jobCreates,0);
 complete(server,first.id,[sample('visual-a','acct-one'),sample('visual-b','acct-one')]);await reopen.run('pollJobs()');assert.equal(reopen.counts().jobCreates,0);assert.equal(reopen.run('jobDetail.results.length'),2);const images=flatten(reopen.els.get('outputs')).filter(e=>e.tag==='img');assert.equal(images.length,2);assert.match(images[0].src,/^data:image\/svg\+xml/);assert.equal(reopen.ctx.window.PWNED,undefined);assert(!flatten(reopen.els.get('outputs')).some(e=>e.tag==='iframe'));
 const raw=reopen.run('jobDetail.results[0].output');flatten(reopen.els.get('outputs')).find(e=>e.tag==='button'&&e.textContent==='导出 HTML').onclick();assert.equal(reopen.els.get('export-content').value,raw);await reopen.run('downloadAll()');assert.equal(JSON.parse(reopen.els.get('export-content').value).item.account_id,'acct-one');reopen.run('copyExport()');assert.match(reopen.els.get('export-note').textContent,/已复制/);
 await flatten(reopen.els.get('outputs')).find(e=>e.tag==='button'&&e.textContent==='绘图正常').onclick();assert.equal(reopen.counts().reviews,1);assert.equal(reopen.run('jobDetail.results[0].assessment.verdict'),'pass');
 await reopen.run('selectJob('+JSON.stringify(second.id)+')');assert.equal(reopen.run('selectedId'),'acct-two');assert(!flatten(reopen.els.get('outputs')).some(e=>String(e.textContent).includes('Pelican acct-one')));assert(flatten(reopen.els.get('identity')).some(e=>e.textContent==='two@example.test'));
 await reopen.run('cancelBatch('+JSON.stringify(batch.id)+')');assert.equal(second.status,'cancelled');assert.equal(first.status,'completed');assert.equal(reopen.counts().jobCancels,1);assert.equal(reopen.counts().jobCreates,0);
 complete(server,second.id,[]);await reopen.run('refresh()');assert.equal(reopen.counts().jobCreates,0);
 // Completed results also restore automatically after a fresh page load, with zero create requests.
 let saved=await boot({server});assert.equal(saved.run('jobDetail.results.length'),2);assert.equal(saved.counts().jobCreates,0);assert.equal(saved.run('jobDetail.results[0].assessment.verdict'),'pass');await saved.run('refresh()');assert.equal(saved.counts().jobCreates,0);assert.equal(saved.run('busy'),false);
 // Each kind, including one account, is a single queued submit, never a browser model-call loop.
 for(const kind of ['fingerprint','logic']){r=await boot();r.run('mode='+JSON.stringify(kind)+';render()');await r.run('submitJobs()');assert.equal(r.counts().jobCreates,1);assert.equal(r.jobPayloads[0].kind,kind);assert.equal(r.jobPayloads[0].repetitions,1);assert.deepEqual(r.jobPayloads[0].account_ids,['acct-one']);assert.equal(r.server.jobs[0].items[0].total,kind==='fingerprint'?3:1);}
 const fpItem=r.server.jobs[0].items[0];complete(r.server,fpItem.id,[sample('logic','acct-one','logic')]);await r.run('pollJobs()');assert(flatten(r.els.get('outputs')).some(e=>e.textContent==='通过'));assert.equal(r.status.accounts[0].quality.phase,'pending');
 r=await boot();r.ctx.crypto={getRandomValues:array=>crypto.getRandomValues(array)};await r.run('submitJobs()');const fp=r.server.jobs[0].items[0],answer={at_ms:Date.now(),challenge_id:'challenge',prompt:'prompt',output:'1, 2, 3 <script>',number_count:300,expected_count:300,error:null};complete(r.server,fp.id,[{account_id:'acct-one',batch:{model:'gpt-test',started_at_ms:Date.now(),completed_at_ms:Date.now(),attempts:[answer,answer,answer],score:{predicted_model:'gpt-test',predicted_probability:.99,expected_probability:.99,candidates:[{model:'gpt-test',probability:.99}]},verdict:'healthy'},quality:r.status.accounts[0].quality}]);await r.run('pollJobs()');assert.equal(r.els.get('score').hidden,false);assert(flatten(r.els.get('outputs')).some(e=>e.textContent==='1, 2, 3 <script>'));assert.equal(r.counts().jobCreates,1);
 r=await boot({server:{...service(),worker_supported:false}});assert.equal(r.els.get('start').disabled,true);assert.equal(r.els.get('worker-notice').hidden,false);assert.match(r.els.get('worker-notice').textContent,/维护 v2/);await r.run('submitJobs()');assert.equal(r.counts().jobCreates,0);
 r=await boot();r.status.budget.attempts=12;await r.run('refresh()');assert.equal(r.els.get('start').disabled,true);await r.run('submitJobs()');assert.equal(r.counts().jobCreates,0);
 // Unknown submit outcomes recover through GET; retrying the exact draft has a stable idempotency key.
 r=await boot({submitFailure:true});await r.run('submitJobs()');const submitId=r.jobPayloads[0].submission_id;assert.match(r.els.get('notice').textContent,/尚未确认/);await r.run('submitJobs()');assert.equal(r.jobPayloads[1].submission_id,submitId);assert.equal(r.server.jobs.length,1);await r.run('refresh()');assert.equal(r.server.jobs.length,1);assert.equal(r.els.get('start').disabled,true);
 for(const code of ['queue_active','job_submission_conflict','job_interrupted_not_replayed','job_configuration_changed','job_cancelled','job_not_found','invalid_job_request','invalid_job_model_or_effort']){r.ctx.testError=code;assert.match(r.run('errorLabel(testError)'),/[\u4e00-\u9fff]/);}
 // Legacy saved evidence remains readable and exports do not enqueue or execute.
 r=await boot();r.status.accounts[1].visual_tests=[sample('legacy','acct-two')];r.run("selectedId='acct-two';mode='visual';render()");await r.run('loadManualEvidence(currentAccount())');assert.equal(r.counts().visualReads,1);await r.run('downloadAll()');assert.equal(JSON.parse(r.els.get('export-content').value).account_id,'acct-two');assert.equal(r.counts().jobCreates,0);
 // Settings use safe controls and a revision-checked six-field patch; hidden rules and spend stay unchanged.
 r=await boot({settingsPage:true,customOutput:3000,missingAccount:true});assert.equal(r.run('settingsOpen'),true);assert.equal(r.counts().settingsReads,1);assert.equal(r.counts().reads,0);assert.equal(r.counts().posts+r.counts().visualPosts+r.counts().logicPosts,0);assert.equal(r.els.get('settings-output').value,'3000');assert(flatten(r.els.get('settings-output')).some(e=>e.value==='3000'));assert.equal(r.els.get('settings-enabled').checked,true);assert.match(r.els.get('settings-token-cap').textContent,/30,000.*当前配置/);
 let choices=flatten(r.els.get('settings-accounts'));assert(choices.some(e=>e.tag==='input'&&e.value==='acct-missing'&&e.checked));assert(choices.some(e=>e.tag==='input'&&e.value==='acct-disabled'&&e.disabled));assert(choices.some(e=>e.textContent==='Unavailable <script>'));assert.match(r.els.get('settings-account-count').textContent,/已选 2/);assert(flatten(r.els.get('settings-fixed')).some(e=>String(e.textContent).includes('实际 Key 预算独立管理')));
 r.run("$('settings-search').value='TWO@EXAMPLE';renderSettingsAccounts()");choices=flatten(r.els.get('settings-accounts'));assert.equal(choices.filter(e=>e.tag==='input').length,1);const two=choices.find(e=>e.tag==='input');two.checked=true;two.onchange();assert.equal(r.run('settingsAccounts.size'),3);r.run("$('settings-search').value='';renderSettingsAccounts()");
 const originalBudget=clone(r.status.budget),fixed=clone(r.settings.fixed);await r.run('saveSettings()');assert.equal(r.counts().settingsPosts,1);assert.deepEqual(Object.keys(r.settingsPayloads[0]).sort(),['expected_revision','enabled','auto_probe','account_ids','model','max_daily_attempts','max_output_tokens'].sort());assert(r.settingsPayloads[0].account_ids.includes('acct-missing'));assert.equal(r.settingsPayloads[0].max_output_tokens,3000);assert.equal(r.settingsPayloads[0].expected_revision,7);assert.deepEqual(r.settings.fixed,fixed);assert.deepEqual(r.status.budget,originalBudget);assert.match(r.els.get('settings-notice').textContent,/保存并读取确认/);assert.equal(r.counts().settingsReads,2);assert.equal(r.counts().posts+r.counts().visualPosts+r.counts().logicPosts,0);
 r.run("$('settings-attempts').value='8';settingsBudget()");assert.match(r.els.get('settings-token-cap').textContent,/24,000.*请求次数/);r.run("settingsAccounts.delete('acct-missing');$('settings-model').value='gpt-6-astra';settingsBudget()");assert.match(r.els.get('settings-changes').textContent,/重新准入.*冷却仍保留/);assert.match(r.els.get('settings-changes').textContent,/取消纳管 1.*清理/);await r.run('saveSettings()');assert.equal(r.settings.fixed.max_daily_output_tokens,24000);assert.equal(r.settings.fixed.confidence_threshold,.99);assert.equal(r.settings.fixed.probe_daily_usd,'5');assert.deepEqual(r.settings.fixed.business_key_ids,['key-untouched']);
 // A stale save preserves every edited control, performs no verification read and does not claim success.
 r=await boot({settingsFailure:'settings_conflict'});await r.run('showSettings()');r.run("$('settings-attempts').value='17';$('settings-auto').value='true';settingsAccounts.add('acct-two')");await r.run('saveSettings()');assert.equal(r.els.get('settings-attempts').value,'17');assert.equal(r.els.get('settings-auto').value,'true');assert.equal(r.run("settingsAccounts.has('acct-two')"),true);assert.match(r.els.get('settings-notice').textContent,/其他页面修改.*填写内容已保留/);assert.equal(r.counts().settingsReads,1);assert.equal(r.run('busy'),false);assert.equal(r.els.get('settings-save').disabled,false);await r.run('leaveSettings()');await r.run('showSettings()');assert.equal(r.els.get('settings-attempts').value,'17');assert.equal(r.counts().settingsReads,1);
 const saves=r.counts().settingsPosts;for(const n of ['', '1.5','10001']){r.run("$('settings-attempts').value="+JSON.stringify(n));await r.run('saveSettings()');assert.equal(r.counts().settingsPosts,saves);assert.match(r.els.get('settings-notice').textContent,/1 至 10000/);}r.run("$('settings-attempts').value='6';settingsAccounts.clear();$('settings-enabled').checked=true");await r.run('saveSettings()');assert.equal(r.counts().settingsPosts,saves);assert.match(r.els.get('settings-notice').textContent,/至少选择一个/);r.run("settingsAccounts=new Set(Array.from({length:101},(_,i)=>'acct-'+i))");await r.run('saveSettings()');assert.match(r.els.get('settings-notice').textContent,/最多选择 100/);assert.equal(r.counts().settingsPosts,saves);
 r.run('busy=true;settingsNavigation()');assert.equal(r.els.get('settings-fields').disabled,true);assert.equal(r.els.get('settings-save').disabled,true);assert.equal(r.els.get('settings-back').disabled,true);await r.run('saveSettings()');assert.equal(r.counts().settingsPosts,saves);await r.run('leaveSettings()');assert.equal(r.run('settingsOpen'),true);r.run('busy=false;settingsNavigation()');await r.run('readSettings()');assert.equal(r.els.get('settings-attempts').value,'6');assert.equal(r.run('settingsAccounts.size'),1);
 assert(!script.includes('.innerHTML'));assert(!script.includes('srcdoc'));assert(!script.includes('createObjectURL'));assert(!script.includes("request('POST','probe'"));assert(!script.includes("request('POST',kind,"));assert(html.includes('prefers-reduced-motion'));assert(html.includes('aria-live="polite"'));
 console.log('UI checks passed: persistent multi-account queue, reload and polling create no jobs or model calls, selected-account evidence isolation, queued cancellation, unsupported-worker and budget guards, idempotent submit retry, safe preview/export/review, legacy evidence and settings preserved.');
})().catch(e=>{console.error(e);process.exitCode=1;});
